import type { Metadata } from "next";
import { geistMono, geistSans } from "@/styles/fonts";
import { Providers } from "./providers";
import "../styles/globals.css";
import "@rainbow-me/rainbowkit/styles.css";

export const metadata: Metadata = {
  title: "Pairs.io",
  description: "Generated by Pairs.io",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
